In [1]:
import pandas as pd

In [2]:
df = pd.read_spss('/data/shared/fsibilla/wfp-da4hd/DATA/in/yem/Yemen MICS6 Datasets/Yemen MICS6 SPSS Datasets/hh.sav')
df.columns

Index(['HH1', 'HH2', 'HH3', 'HH4', 'HH5D', 'HH5M', 'HH5Y', 'HH6', 'HH7',
       'HH11H',
       ...
       'windex5', 'windex10', 'wscoreu', 'windex5u', 'windex10u', 'wscorer',
       'windex5r', 'windex10r', 'PSU', 'stratum'],
      dtype='object', length=278)

In [3]:
df.head()

,HH1,HH2,HH3,HH4,HH5D,HH5M,HH5Y,HH6,HH7,HH11H,...,windex5,windex10,wscoreu,windex5u,windex10u,wscorer,windex5r,windex10r,PSU,stratum
0,1.0,1.0,102.0,101.0,9.0,2.0,2023.0,URBAN,Ibb,12.0,...,Richest,10th decile,0.891010,Richest,10th decile,NaN,NaN,NaN,1.0,1.0
1,1.0,2.0,102.0,101.0,9.0,2.0,2023.0,URBAN,Ibb,11.0,...,Fourth,8th decile,-0.082171,Second,4th decile,NaN,NaN,NaN,1.0,1.0
2,1.0,3.0,102.0,101.0,9.0,2.0,2023.0,URBAN,Ibb,9.0,...,Richest,9th decile,0.464062,Fourth,7th decile,NaN,NaN,NaN,1.0,1.0
3,1.0,4.0,102.0,101.0,9.0,2.0,2023.0,URBAN,Ibb,10.0,...,Richest,10th decile,0.913205,Richest,10th decile,NaN,NaN,NaN,1.0,1.0
4,1.0,5.0,103.0,101.0,9.0,2.0,2023.0,URBAN,Ibb,11.0,...,Fourth,8th decile,-0.179987,Second,3rd decile,NaN,NaN,NaN,1.0,1.0

In [4]:
df=df[['HH7','wscore']]

In [5]:
result = (
    df.groupby("HH7", as_index=False)
      .mean(numeric_only=True)
)

/tmp/ipykernel_1697328/1875009710.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("HH7", as_index=False)

In [6]:
result

            HH7    wscore
0         Abyan  0.436440
1          Aden  1.146115
2      Al Bayda  0.094529
3    Al Dhale'e -0.205586
4   Al Hudaydah -0.155019
5       Al Jawf -0.951820
6    Al Maharah  0.665844
7     Al Mahwit -0.586501
8         Amran -0.348794
9        Dhamar -0.398291
10    Hadramaut  1.143380
11       Hajjah -0.840966
12          Ibb -0.061354
13         Lahj  0.088229
14        Marib -0.149481
15       Raymah -0.999574
16       Sa'ada -0.345844
17       Sana'a -0.398529
18  Sana'a City  1.038786
19      Shabwah  0.465783
20      Socotra  0.202615
21        Taizz -0.144927

In [7]:
result.to_csv('/data/shared/fsibilla/DATA_PROCESSING/yem_mvam/adm1_mics_wscore.csv',index=False)